packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild

catalog:
  typescript: '^5.9.3'
  vitest: '^4.1.5'
  zod: '^3.25.76'
  axios: '^1.15.2'
  date-fns: '^4.1.0'
  tsup: '^8.5.1'
  tsx: '^4.21.0'
  '@types/node': '^25.6.0'

catalogs:
  eslint:
    eslint: '^9.39.4'
    typescript-eslint: '^8.59.1'
    '@typescript-eslint/parser': '^8.59.1'
    '@typescript-eslint/eslint-plugin': '^8.59.1'
    eslint-plugin-n: '^17.24.0'
    eslint-plugin-react: '^7.37.5'
    eslint-plugin-react-hooks: '^7.1.1'
    '@vitest/eslint-plugin': '^1.6.16'
